"""user add confirmation field

Revision ID: 5676daf39a14
Revises: bd50a7800186
Create Date: 2022-02-19 17:31:17.124751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5676daf39a14'
down_revision = 'bd50a7800186'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('activated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'activated')
    # ### end Alembic commands ###
